/** Audit action constants — referenced by services when writing audit logs. */
export const AUDIT_ACTIONS = {
  // Auth
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",

  // Platform / organizations
  ORGANIZATION_CREATE: "ORGANIZATION_CREATE",
  ORGANIZATION_UPDATE: "ORGANIZATION_UPDATE",
  ORGANIZATION_SUSPEND: "ORGANIZATION_SUSPEND",
  ORGANIZATION_ACTIVATE: "ORGANIZATION_ACTIVATE",

  // Branches
  BRANCH_CREATE: "BRANCH_CREATE",
  BRANCH_UPDATE: "BRANCH_UPDATE",
  BRANCH_APPROVE: "BRANCH_APPROVE",
  BRANCH_REJECT: "BRANCH_REJECT",

  // Users / RBAC
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  ROLE_CHANGE: "ROLE_CHANGE",
  PERMISSION_CHANGE: "PERMISSION_CHANGE",

  // Patients
  PATIENT_CREATE: "PATIENT_CREATE",
  PATIENT_UPDATE: "PATIENT_UPDATE",
  PATIENT_DELETE: "PATIENT_DELETE",

  // Test catalog
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",
  TEST_CREATE: "TEST_CREATE",
  TEST_UPDATE: "TEST_UPDATE",
  TEST_DELETE: "TEST_DELETE",

  // Orders
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_UPDATE: "ORDER_UPDATE",
  ORDER_CANCEL: "ORDER_CANCEL",

  // Samples
  SAMPLE_CREATE: "SAMPLE_CREATE",
  SAMPLE_COLLECT: "SAMPLE_COLLECT",
  SAMPLE_RECEIVE: "SAMPLE_RECEIVE",
  SAMPLE_REJECT: "SAMPLE_REJECT",

  // Results
  RESULT_CREATE: "RESULT_CREATE",
  RESULT_MODIFY: "RESULT_MODIFY",
  RESULT_PREPARE: "RESULT_PREPARE",
  RESULT_APPROVE: "RESULT_APPROVE",
  RESULT_REJECT: "RESULT_REJECT",
  RESULT_RELEASE: "RESULT_RELEASE",
  RESULT_SEND: "RESULT_SEND",

  // Payments
  PAYMENT_CREATE: "PAYMENT_CREATE",
  PAYMENT_UPDATE: "PAYMENT_UPDATE",

  // Branding / settings
  LETTERHEAD_UPDATE: "LETTERHEAD_UPDATE",

  // Subscriptions
  SUBSCRIPTION_CREATE: "SUBSCRIPTION_CREATE",
  SUBSCRIPTION_UPDATE: "SUBSCRIPTION_UPDATE",
  SUBSCRIPTION_RENEW: "SUBSCRIPTION_RENEW",
  SUBSCRIPTION_RENEWAL_PENDING: "SUBSCRIPTION_RENEWAL_PENDING",
  SUBSCRIPTION_STATUS_CHANGE: "SUBSCRIPTION_STATUS_CHANGE",
};

export default AUDIT_ACTIONS;
