export const CENTRES = [
  {
    id: "c1",
    name: "Aguda Lab",
    city: "Lagos",
    phone: "+2348033812170",
    email: "foundation.laboratory@yahoo.com",
    manager: "Mrs. Judith N. Obiorah (BMLS)",
    status: "active",
    patientsToday: 47,
  },
  {
    id: "c3",
    name: "Bode Thomas Lab",
    city: "Lagos",
    phone: "+2348033812170",
    email: "foundation.laboratory@yahoo.com",
    manager: "Mrs. Judith N. Obiorah (BMLS)",
    status: "active",
    patientsToday: 28,
  },
];

export const USERS = [
  {
    id: "u1",
    name: "Mrs. Judith N. Obiorah (BMLS)",
    email: "judith.obiorah@foundationlab.com",
    role: "admin",
    centre: "Aguda Lab",
    status: "active",
  },
  {
    id: "u2",
    name: "Grace Anyaoba",
    email: "grace.anyaoba@gmail.com",
    role: "receptionist",
    centre: "Aguda Lab",
    status: "active",
  },
  {
    id: "u3",
    name: "Sidikat Olowoporoku",
    email: "sidikat.olowoporoku@gmail.com",
    role: "phlebotomist",
    centre: "Aguda Lab",
    status: "active",
  },
  {
    id: "u4",
    name: "Mercy Akiniyi",
    email: "mercy.akiniyi@gmail.com",
    role: "lab_tech",
    centre: "Aguda Lab",
    status: "active",
  },
  {
    id: "u5",
    name: "Peter Malomo",
    email: "peter.malomo@gmail.com",
    role: "radiographer",
    centre: "Aguda Lab",
    status: "active",
  },
  {
    id: "u6",
    name: "Susan Batholomew",
    email: "susan.batholomew@gmail.com",
    role: "receptionist",
    centre: "Bode Thomas Lab",
    status: "active",
  },
  {
    id: "u7",
    name: "Kevin Ikeduba",
    email: "kevin.ikeduba@gmail.com",
    role: "lab_tech",
    centre: "Bode Thomas Lab",
    status: "active",
  },
];

export const PATIENTS = [
  {
    id: "p1",
    pid: "PID-0041",
    name: "Amina Hassan",
    dob: "1985-03-12",
    gender: "Female",
    phone: "+234 701 234 5678",
    email: "amina.hassan@gmail.com",
    centre: "Aguda Lab",
    lastVisit: "2026-06-10",
    tests: 5,
  },
  {
    id: "p2",
    pid: "PID-0042",
    name: "John Chibuzor",
    dob: "1972-07-22",
    gender: "Male",
    phone: "+234 723 456 7389",
    email: "john.chibuzor@gmail.com",
    centre: "Aguda Lab",
    lastVisit: "2026-06-11",
    tests: 3,
  },
  {
    id: "p3",
    pid: "PID-0043",
    name: "Fatima Abdullah",
    dob: "1990-11-05",
    gender: "Female",
    phone: "+234 734 567 8090",
    email: "fatima.abdullah@gmail.com",
    centre: "Aguda Lab",
    lastVisit: "2026-06-12",
    tests: 8,
  },
  {
    id: "p4",
    pid: "PID-0044",
    name: "Robert Thomas",
    dob: "1965-01-18",
    gender: "Male",
    phone: "+234 745 678 9201",
    email: "robert.thomas@gmail.com",
    centre: "Bode Thomas Lab",
    lastVisit: "2026-06-13",
    tests: 2,
  },
  {
    id: "p5",
    pid: "PID-0045",
    name: "Mary Onjeru",
    dob: "1998-09-30",
    gender: "Female",
    phone: "+234 756 789 0122",
    email: "mary.onjeru@gmail.com",
    centre: "Aguda Lab",
    lastVisit: "2026-06-14",
    tests: 1,
  },
  {
    id: "p6",
    pid: "PID-0046",
    name: "David Ayangbure",
    dob: "1980-04-15",
    gender: "Male",
    phone: "+234 767 890 1123",
    email: "david.ayangbure@gmail.com",
    centre: "Bode Thomas Lab",
    lastVisit: "2026-06-14",
    tests: 6,
  },
  {
    id: "p7",
    pid: "PID-0047",
    name: "Jamiu Alabi",
    dob: "1995-08-22",
    gender: "Female",
    phone: "+234 778 901 2234",
    email: "jamiu.alabi@gmail.com",
    centre: "Bode Thomas Lab",
    lastVisit: "2026-06-09",
    tests: 4,
  },
];

export const TESTS = [
  {
    id: "t1",
    code: "CBC-001",
    name: "Complete Blood Count (CBC)",
    category: "Haematology",
    price: "₦1200",
    turnaround: "4 hrs",
    sampleType: "Whole Blood",
  },
  {
    id: "t2",
    code: "LFT-002",
    name: "Liver Function Tests",
    category: "Biochemistry",
    price: "₦2500",
    turnaround: "6 hrs",
    sampleType: "Serum",
  },
  {
    id: "t3",
    code: "KFT-003",
    name: "Kidney Function Tests",
    category: "Biochemistry",
    price: "₦2200",
    turnaround: "6 hrs",
    sampleType: "Serum",
  },
  {
    id: "t4",
    code: "FBS-004",
    name: "Fasting Blood Sugar",
    category: "Biochemistry",
    price: "₦600",
    turnaround: "2 hrs",
    sampleType: "Serum",
  },
  {
    id: "t5",
    code: "TSH-005",
    name: "Thyroid Stimulating Hormone",
    category: "Endocrinology",
    price: "₦3500",
    turnaround: "8 hrs",
    sampleType: "Serum",
  },
  {
    id: "t6",
    code: "URI-006",
    name: "Urinalysis",
    category: "Microbiology",
    price: "₦800",
    turnaround: "2 hrs",
    sampleType: "Urine",
  },
  {
    id: "t7",
    code: "XRY-007",
    name: "Chest X-Ray",
    category: "Radiology",
    price: "₦4500",
    turnaround: "1 hr",
    sampleType: "N/A",
  },
  {
    id: "t8",
    code: "ULS-008",
    name: "Abdominal Ultrasound",
    category: "Radiology",
    price: "₦6000",
    turnaround: "1 hr",
    sampleType: "N/A",
  },
  {
    id: "t9",
    code: "HBA-009",
    name: "HbA1c",
    category: "Endocrinology",
    price: "₦2800",
    turnaround: "4 hrs",
    sampleType: "Whole Blood",
  },
  {
    id: "t10",
    code: "LPS-010",
    name: "Lipid Profile",
    category: "Biochemistry",
    price: "₦2000",
    turnaround: "6 hrs",
    sampleType: "Serum",
  },
];

export const TEST_ORDERS = [
  {
    id: "o1",
    orderId: "ORD-2026-0141",
    patientId: "p1",
    patientName: "Amina Hassan",
    centre: "Bode Thomas Lab",
    date: "2026-06-14",
    totalAmount: "₦4,900",
    paymentStatus: "paid",
    items: [
      {
        id: "oi1",
        testId: "t1",
        testName: "CBC",
        price: "₦1,200",
        status: "completed",
      },
      {
        id: "oi2",
        testId: "t2",
        testName: "LFT",
        price: "₦2,500",
        status: "completed",
      },
      {
        id: "oi3",
        testId: "t4",
        testName: "FBS",
        price: "₦6,000",
        status: "completed",
      },
    ],
  },
  {
    id: "o2",
    orderId: "ORD-2026-0142",
    patientId: "p2",
    patientName: "John Chibuzor",
    centre: "Aguda Lab",
    date: "2026-06-14",
    totalAmount: "₦3,500",
    paymentStatus: "pending",
    items: [
      {
        id: "oi4",
        testId: "t5",
        testName: "TSH",
        price: "₦3,500",
        status: "processing",
      },
    ],
  },
  {
    id: "o3",
    orderId: "ORD-2026-0143",
    patientId: "p3",
    patientName: "Fatima Abdullah",
    centre: "Bode Thomas Lab",
    date: "2026-06-13",
    totalAmount: "₦8,500",
    paymentStatus: "paid",
    items: [
      {
        id: "oi5",
        testId: "t7",
        testName: "Chest X-Ray",
        price: "₦4,500",
        status: "completed",
      },
      {
        id: "oi6",
        testId: "t3",
        testName: "KFT",
        price: "₦2,200",
        status: "pending",
      },
      {
        id: "oi7",
        testId: "t6",
        testName: "Urinalysis",
        price: "₦8,000",
        status: "collected",
      },
    ],
  },
  {
    id: "o4",
    orderId: "ORD-2026-0144",
    patientId: "p4",
    patientName: "Robert Thomas",
    centre: "Aguda Lab",
    date: "2026-06-13",
    totalAmount: "₦6,000",
    paymentStatus: "partial",
    items: [
      {
        id: "oi8",
        testId: "t8",
        testName: "Abdominal Ultrasound",
        price: "₦6000",
        status: "pending",
      },
    ],
  },
  {
    id: "o5",
    orderId: "ORD-2026-0145",
    patientId: "p5",
    patientName: "Mary Onjeru",
    centre: "Bode Thomas Lab",
    date: "2026-06-12",
    totalAmount: "₦2,800",
    paymentStatus: "paid",
    items: [
      {
        id: "oi9",
        testId: "t9",
        testName: "HbA1c",
        price: "₦2,800",
        status: "completed",
      },
    ],
  },
];

export const RESULTS = [
  {
    id: "r1",
    orderId: "ORD-2026-0141",
    patientName: "Amina Hassan",
    testName: "Complete Blood Count",
    centre: "Bode Thomas Lab",
    date: "2026-06-14",
    status: "ready",
    fileType: "pdf",
  },
  {
    id: "r2",
    orderId: "ORD-2026-0141",
    patientName: "Amina Hassan",
    testName: "Liver Function Tests",
    centre: "Bode Thomas Lab",
    date: "2026-06-14",
    status: "ready",
    fileType: "pdf",
  },
  {
    id: "r3",
    orderId: "ORD-2026-0143",
    patientName: "Fatima Abdullah",
    testName: "Chest X-Ray",
    centre: "Bode Thomas Lab",
    date: "2026-06-14",
    status: "reviewed",
    fileType: "image",
  },
  {
    id: "r4",
    orderId: "ORD-2026-0145",
    patientName: "Mary Onjeru",
    testName: "HbA1c",
    centre: "Bode Thomas Lab",
    date: "2026-06-13",
    status: "ready",
    fileType: "pdf",
  },
  {
    id: "r5",
    orderId: "ORD-2026-0142",
    patientName: "John Chibuzor",
    testName: "TSH",
    centre: "Aguda Lab",
    date: "2026-06-14",
    status: "pending",
    fileType: "pdf",
  },
];

export const PAYMENTS = [
  {
    id: "pay1",
    orderId: "ORD-2026-0141",
    patientName: "Amina Hassan",
    amount: "₦4,900",
    method: "card",
    status: "completed",
    date: "2026-06-14",
    centre: "Bode Thomas Lab",
  },
  {
    id: "pay2",
    orderId: "ORD-2026-0143",
    patientName: "Fatima Abdullah",
    amount: "₦8,500",
    method: "cash",
    status: "completed",
    date: "2026-06-13",
    centre: "Bode Thomas Lab",
  },
  {
    id: "pay3",
    orderId: "ORD-2026-0145",
    patientName: "Mary Onjeru",
    amount: "₦2,800",
    method: "mobile",
    status: "completed",
    date: "2026-06-12",
    centre: "Bode Thomas Lab",
  },
  {
    id: "pay4",
    orderId: "ORD-2026-0144",
    patientName: "Robert Thomas",
    amount: "₦3,000",
    method: "cash",
    status: "completed",
    date: "2026-06-13",
    centre: "Aguda Lab",
  },
  {
    id: "pay5",
    orderId: "ORD-2026-0142",
    patientName: "John Chibuzor",
    amount: "₦10,000",
    method: "card",
    status: "pending",
    date: "2026-06-14",
    centre: "Aguda Lab",
  },
];

export const AUDIT_LOGS = [
  {
    id: "a1",
    user: "Grace Anyaoba",
    action: "Created",
    entity: "TestOrder",
    entityId: "ORD-2026-0141",
    date: "2026-06-14",
    time: "08:32:14",
    centre: "Bode Thomas Lab",
  },
  {
    id: "a2",
    user: "Sidikat Olowoporoku",
    action: "Updated",
    entity: "OrderItem",
    entityId: "OI-001",
    date: "2026-06-14",
    time: "09:15:42",
    centre: "Aguda Lab",
  },
  {
    id: "a3",
    user: "Mercy Akiniyi",
    action: "Uploaded",
    entity: "Result",
    entityId: "RES-0141",
    date: "2026-06-14",
    time: "10:44:07",
    centre: "Aguda Lab",
  },
  {
    id: "a4",
    user: "Mrs. Judith N. Obiorah (BMLS)",
    action: "Approved",
    entity: "Result",
    entityId: "RES-0143",
    date: "2026-06-13",
    time: "16:02:33",
    centre: "Bode Thomas Lab",
  },
  {
    id: "a5",
    user: "Grace Anyaoba",
    action: "Created",
    entity: "Patient",
    entityId: "PID-0047",
    date: "2026-06-13",
    time: "14:21:55",
    centre: "Aguda Lab",
  },
  {
    id: "a6",
    user: "Peter Malomo",
    action: "Uploaded",
    entity: "Result",
    entityId: "RES-0143",
    date: "2026-06-14",
    time: "11:30:19",
    centre: "Aguda Lab",
  },
];

export const revenueData = [
  { month: "Jan", Aguda: 2000000, BodeThomas: 1900000 },
  { month: "Feb", Aguda: 1350000, BodeThomas: 2000000 },
  { month: "Mar", Aguda: 1280000, BodeThomas: 890000 },
  { month: "Apr", Aguda: 1420000, BodeThomas: 1050000 },
  { month: "May", Aguda: 1580000, BodeThomas: 1110000 },
  { month: "Jun", Aguda: 2650000, BodeThomas: 2180000 },
];

export const testsByCategoryData = [
  { name: "Biochemistry", value: 34 },
  { name: "Haematology", value: 22 },
  { name: "Radiology", value: 18 },
  { name: "Endocrinology", value: 14 },
  { name: "Microbiology", value: 12 },
];

export const testsByDayData = [
  { day: "Mon", tests: 58 },
  { day: "Tue", tests: 72 },
  { day: "Wed", tests: 65 },
  { day: "Thu", tests: 81 },
  { day: "Fri", tests: 94 },
  { day: "Sat", tests: 47 },
  { day: "Sun", tests: 23 },
];

export const PIE_COLORS = [
  "#1a6bcc",
  "#0ea5a0",
  "#7c3aed",
  "#f59e0b",
  "#10b981",
];
